# Generated by Django 4.2.5 on 2023-09-26 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='genre',
        ),
    ]
