# Generated by Django 4.2.5 on 2023-10-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='any-book', max_length=140, unique=True),
            preserve_default=False,
        ),
    ]
