# Generated by Django 4.2.5 on 2023-10-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_genre_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='uncategorised', max_length=100, unique=True),
        ),
    ]
