# Generated by Django 4.2.5 on 2023-09-27 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_cart_user_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-quantity']},
        ),
    ]
