version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: joyboy
      MYSQL_PASSWORD: password
    ports:
      - "3306:3366"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app  # Adjust this path based on your project structure
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

volumes:
  mysql_data:
