name: ci-cd-storyKeeper
on: 
    push:
        branches: master
jobs:
    upload-code-to-server:
        runs-on: ubuntu-latest
        env:
            DOMAIN: bcohort.com 
        steps:
          - name: Checkout repo
            uses: actions/checkout@v2  
          - name: Run test Deployment
            run: |
                ssh -i ${{ secrets.BLOGGING_SERVER_SSH_KEY }} ubuntu@${{ env.DOMAIN }} 'bash -s' < /home/ubuntu/online-book-store/deploy_script.sh true
            env:
                ACTIONS_RUNNER_DEBUG: true
